const CONTENT_IMAGE = 'IMAGE';
const CONTENT_VIDEO = 'VIDEO';
const CONTENT_STICKER = 'STICKER';
const CONTENT_COUPON = 'COUPON';
const CONTENT_LINK = 'LINK';
const CONTENT_SURVEY = 'SURVEY';

export {
    CONTENT_IMAGE,
    CONTENT_VIDEO,
    CONTENT_STICKER,
    CONTENT_COUPON,
    CONTENT_LINK,
    CONTENT_SURVEY
};
